export const data = [
     {
    question: "Which country is famous for the Great Wall?",
    option1: "India",
    option2: "China",
    option3: "Japan",
    option4: "Thailand",
    ans: 2,
  },
  {
    question: "How many continents are there in the world?",
    option1: "5",
    option2: "6",
    option3: "7",
    option4: "8",
    ans: 3,
  },
    {
        question: "A Computer Cannot BOOT if it does not have the?",
        option1: "Application Software",
        option2: "Internet",
        option3: "Operating System",
        option4: "Mouse",
        ans: 3,
    },
    {
        question: "First Page of Website is Termed as ?",
        option1: "Index Page",
        option2: "HomePage",
        option3: "Sitemap",
        option4: "Pen Drive",
        ans: 2,
    },
      {
    question: "Who wrote the national anthem of India?",
    option1: "Rabindranath Tagore",
    option2: "Mahatma Gandhi",
    option3: "Bankim Chandra Chatterjee",
    option4: "Subhash Chandra Bose",
    ans: 1,
  },
  {
    question: "Which gas do plants absorb during photosynthesis?",
    option1: "Oxygen",
    option2: "Nitrogen",
    option3: "Carbon Dioxide",
    option4: "Hydrogen",
    ans: 3,
  },
  {
    question: "What is the largest ocean in the world?",
    option1: "Indian Ocean",
    option2: "Atlantic Ocean",
    option3: "Pacific Ocean",
    option4: "Arctic Ocean",
    ans: 3,
  },
  {
    question: "Which animal is known as the King of the Jungle?",
    option1: "Tiger",
    option2: "Elephant",
    option3: "Lion",
    option4: "Leopard",
    ans: 3,
  },
  {
    question: "What is the chemical symbol for water?",
    option1: "O2",
    option2: "H2O",
    option3: "CO2",
    option4: "NaCl",
    ans: 2,
  },
  {
    question: "Who was the first person to walk on the Moon?",
    option1: "Neil Armstrong",
    option2: "Buzz Aldrin",
    option3: "Yuri Gagarin",
    option4: "Michael Collins",
    ans: 1,
  },

];